// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uqibgkkkthedseeoyzpn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVxaWJna2trdGhlZHNlZW95enBuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzUwNTI3NjAsImV4cCI6MjA1MDYyODc2MH0.3FjvDw4lLmPVk42Sh4XY4Ub_2kJNKP1oIyaeYBBPjeQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);